apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: swuu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swuu
    app.kubernetes.io/part-of: byoc-app-noye
  name: swuu
spec:
  rules:
  - host: swuu-byoc-xtba-tenant.apps.08dd72d15329319aab56.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: swuu
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
