apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: swuu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: swuu
    app.kubernetes.io/part-of: byoc-app-noye
  name: swuu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: swuu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: swuu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-xtba-tenant/byoc-app-noye/swuu@sha256:af00e34318e9af9d3ce13f9b069257683e386a21421ad7e02c159e184360d580
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
